### ISSUE TITLE
program do not open

### ISSUE THREAD

**Issue by denielton** [snapcrafters/photoscape#3]
Kubuntu 18.04 
-----------------

I installed photoscape with the command on terminal
sudo snap install photoscape

after that, i tried to open photoscape and it just load and do not open, here's the log:
[photoscape log.txt](https://github.com/snapcrafters/photoscape/files/2999954/photoscape.log.txt)

**Comment by RobotasIrgiZmogus** [comment]
Same here. The spinner spins for a couple of seconds and dies. It worked several months ago.

**Comment by pavakpaul** [comment]
Same problem. It's simply doesn't open. Terminal output: https://paste.ubuntu.com/p/cSkZZQbMwF/

**Comment by merlijn-sebrechts** [comment]
Thanks for the bug report!

I wanted to give you a heads up that I'm working on a fix; I'm recreating the snap so that photoscape is part of the snap instead of downloaded when you first run it. I'll let you know when it's finished.

**Comment by merlijn-sebrechts** [comment]
This should be fixed now. Please reopen the issue if you still can't start Photoscape.
