### ISSUE TITLE
Can not use non asciii fonts on text objects

### ISSUE THREAD

**Issue by iercan** [snapcrafters/photoscape#5]
Is it possible to use non ascii (i.e. thai language) on text object? I am not able to use any nonascii fonts.

**Comment by merlijn-sebrechts** [comment]
Hi @ibotheperfect !

Thanks for reaching out. I'd really like to support Thai language, though I don't know a lot about non-latin languages.

How does this work in Libreoffice or another drawing program? Does Thai language in Libreoffice have specific fonts that you use, or does every font in libreoffice support Thai language? Is your language in Ubuntu itself Thai?

Have you ever used Photoscape on Windows, and if so, does it support thai language on Windows?

Thanks for your help!

**Comment by iercan** [comment]
My computer language is English. I added Thai as second keyboard language. In libreoffice or any other program I can use it with any font without any problem.  I didn't try it on windows.
I feel like it is because wine and its language supports.

**Comment by merlijn-sebrechts** [comment]
Sadly, this seems to be an issue with PhotoScape itself, not with the Wine wrapper. This is what I get when I type thai text in PhotoScape in Windows:

![image](https://user-images.githubusercontent.com/1492981/85640795-0a705780-b68d-11ea-898d-5c9e716fc0ea.png)

I am not the developer of PhotoScape, and the developer has more or less abandoned this version of PhotoScape, so I don't think it will ever be added.

I'm closing this issue now. If anyone finds a way to make Thai text work in PhotoScape on Windows, please let me know and I'll take a look if I can replicate it in this snap.
