### ISSUE TITLE
How to access my Linux printer(s)

### ISSUE THREAD

**Issue by kev005** [snapcrafters/photoscape#6]
I installed Photoscape's snap, but do not see a plug  for cups-control, so I cannot print.  Installing in crossover Linux gives access to the wine control-panel, so I configure printing, but I prefer to use the snap you provided.  This is under Manjaro  21.0.

**Comment by merlijn-sebrechts** [comment]
Hi @kev005 

Thanks for reporting this issue. I have added the `cups` and `cups-control` plugs to the snap, so you should be able to enable them and print. Let me know if you have any more issues.

You can update the snap by running `snap refresh photoscape`.

Though I'd like to add that, without CrossOver, Wine would not exist which means this snap would not exist so it's always good to support them :wink:
